dose_ml:
  name: Manual dose (mL)
  description: One-shot dose on the selected channel.
  fields:
    device_id:
      name: Device
      description: (Optional) Pick the doser device (resolves BLE address)
      selector:
        device: {}
    address:
      name: BLE address
      description: (Optional) Use if you don’t select a device
      example: "AA:BB:CC:DD:EE:FF"
    channel:
      name: Channel
      required: true
      selector:
        number:
          min: 1
          max: 4
          step: 1
    ml:
      name: Millilitres
      required: true
      selector:
        number:
          min: 0.2
          max: 999.9
          step: 0.1
          mode: box

enable_auto_mode:
  name: Enable auto mode
  description: Switch a dosing channel into auto mode and sync device time.
  fields:
    device_id:
      name: Device
      description: (Optional) Pick the doser device (resolves BLE address)
      selector:
        device: {}
    address:
      name: BLE address
      description: (Optional) Use if you don’t select a device
      example: "AA:BB:CC:DD:EE:FF"
    channel:
      name: Channel
      required: true
      selector:
        number:
          min: 1
          max: 4
          step: 1

read_auto_settings:
  name: Read auto schedule (passive)
  description: Listen briefly and print any observed auto schedules.
  fields:
    device_id:
      name: Device
      description: (Optional) Pick the doser device (resolves BLE address)
      selector:
        device: {}
    address:
      name: BLE address
      description: (Optional) Use if you don’t select a device
      example: "AA:BB:CC:DD:EE:FF"
    channel:
      name: Channel (optional)
      required: false
      selector:
        number:
          min: 1
          max: 4
          step: 1
    timeout_s:
      name: Listen window (seconds)
      required: false
      default: 2.0
      selector:
        number:
          min: 0.2
          max: 30
          step: 0.1
          mode: slider

read_container_status:
  name: Read container/tank status (passive)
  description: Listen briefly and print any container/tank notifications observed.
  fields:
    device_id:
      name: Device
      description: (Optional) Pick the doser device (resolves BLE address)
      selector:
        device: {}
    address:
      name: BLE address
      description: (Optional) Use if you don’t select a device
      example: "AA:BB:CC:DD:EE:FF"
    channel:
      name: Channel (optional)
      required: false
      selector:
        number:
          min: 1
          max: 4
          step: 1
    timeout_s:
      name: Listen window (seconds)
      required: false
      default: 2.0
      selector:
        number:
          min: 0.2
          max: 30
          step: 0.1
          mode: slider

raw_doser_command:
  name: Send raw A5/5B frame
  description: Advanced—send a raw command frame to the doser (for debugging).
  fields:
    device_id:
      name: Device
      description: (Optional) Pick the doser device (resolves BLE address)
      selector:
        device: {}
    address:
      name: BLE address
      description: (Optional) Use if you don’t select a device
      example: "AA:BB:CC:DD:EE:FF"
    cmd_id:
      name: Command ID
      required: true
      selector:
        number:
          min: 0
          max: 255
          step: 1
    mode:
      name: Mode
      required: true
      selector:
        number:
          min: 0
          max: 255
          step: 1
    params:
      name: Parameters (list of bytes)
      description: Provide a YAML/JSON list of integers, e.g. [0, 1, 14, 2, 0, 0]
      required: true
      selector:
        object: {}
    repeats:
      name: Repeats
      required: false
      default: 1
      selector:
        number:
          min: 1
          max: 20
          step: 1

# --- DISABLED: read_daily_totals ---
# (kept for reference; not registered)
# read_daily_totals:
#   ...

# --- DISABLED: set_24h_dose ---
# (kept for reference; not registered)
# set_24h_dose:
#   ...
